let homes = [
    {
      jobColor: '',
      jobName: '645 Athens Dr',
      streetAddress: '645 Athens Dr',
      city: '',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44250.4951388889',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: '',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '21',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Belmont Heights Ph. 7',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '*2046 2A',
      streetAddress: '',
      city: '',
      projectManager: '',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '44231',
      created: '44230.6291666667',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '44231',
      company: '',
      listingAgent: '',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: '',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '*2122 2A',
      streetAddress: '',
      city: '',
      projectManager: '',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '44232',
      created: '44230.5916666667',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '44232',
      company: '',
      listingAgent: '',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: '',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7610 Massey Dr/Pro Made',
      streetAddress: '7610 Massey Dr',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3861111111',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '59',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7614 Massey Dr/Pro Made',
      streetAddress: '7614 Massey Dr',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3847222222',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '60',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7618 Massey Dr/Pro Made',
      streetAddress: '7618 Massey Dr',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3833333333',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '61',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7702 Massey Dr/Pro made',
      streetAddress: '7702 Massey Dr',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3819444444',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '62',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3506 Lakelse Ln/Pro Made',
      streetAddress: '3506 Lakelse Ln',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3777777778',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '2',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3510 Lakelse Ln/Pro Made',
      streetAddress: '3510 Lakelse Ln',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3673611111',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '3',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3604 Lakelse Ln/Pro Made',
      streetAddress: '3604 Lakelse Ln',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3645833333',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '4',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3612 Lakelse ln/Pro Made',
      streetAddress: '3612 Lakelse Ln',
      city: '',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3590277778',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '6',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3616 Lakelse Ln/Pro Made',
      streetAddress: '3616 Lakelse Ln',
      city: '44250',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3569444444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20 SF',
      garageSf: '468 SF',
      lotNumber: '7',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3702 Lakelse ln/Pro Made',
      streetAddress: '3702 Lakelse Ln',
      city: '44246',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3520833333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '468',
      lotNumber: '9',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3706 Lakelse ln/Pro Made',
      streetAddress: '3706 Lakelse Ln',
      city: '44250',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3444444444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '468',
      lotNumber: '10',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3710 Lakelse Ln/Pro Made',
      streetAddress: '3710 Lakelse Ln',
      city: '44251',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3361111111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '116',
      garageSf: '468',
      lotNumber: '11',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7702 Coldwater Dr/Pro Made',
      streetAddress: '7702 Coldwater Dr',
      city: '44251',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44230.3263888889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '15',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1766 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7706 Coldwater Dr/Pro Made',
      streetAddress: '7706 Coldwater Dr',
      city: '44246',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44229.7368055556',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '513',
      lotNumber: '15',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1586 2BSI9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7726 Coldwater Dr/Pro Made',
      streetAddress: '7726 Coldwater Dr',
      city: '',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44229.6895833333',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '21',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7730 Coldwater Dr/Pro Made',
      streetAddress: '7730 Coldwater Dr',
      city: '44250',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44229.6729166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '22',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7814 Waxwing Dr/Pro Made',
      streetAddress: '7814 Waxwing Dr',
      city: '44249',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44229.6694444444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '143',
      garageSf: '742',
      lotNumber: '26',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1598 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7900 Waxwing Dr/Pro Made',
      streetAddress: '7900 Waxwing Dr',
      city: '',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44229.6645833333',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '27',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7611 Coldwater Dr/Pro Made',
      streetAddress: '7611 Coldwater Dr',
      city: '44225',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1766',
      actualCompletion: '',
      actualStart: '',
      created: '44225.5083333333',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '166',
      garageSf: '625',
      lotNumber: '40',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44231',
      modelNumber: '1766 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3565 Curtis Dr/Infinity',
      streetAddress: '3565 Curtis Dr',
      city: '44225',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1869',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4826388889',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '628',
      lotNumber: '16',
      parcelNumber: '118981130000016',
      permit: '',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '',
      utilitiesSent: '44231',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7703 Coldwater Dr/Pro Made',
      streetAddress: '7703 Coldwater Dr',
      city: '44225',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1938',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4597222222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '669',
      lotNumber: '39',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1938 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3707 Lakelse Ln/Pro Made',
      streetAddress: '3707 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '2349',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4402777778',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '691',
      lotNumber: '48',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '2349 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3502 Lakelse Ln/Pro Made',
      streetAddress: '3502 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1598',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4305555556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '143',
      garageSf: '644',
      lotNumber: '1',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44231',
      modelNumber: '1598 2ASI8',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3714 Lakelse Ln/Pro Made',
      streetAddress: '3714 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '2046',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4118055556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '71',
      garageSf: '659',
      lotNumber: '12',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '2046 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7602 Massey Dr/Pro Made',
      streetAddress: '7602 Massey Dr',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '2046',
      actualCompletion: '',
      actualStart: '',
      created: '44225.4090277778',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '213',
      garageSf: '678',
      lotNumber: '57',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '2046 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7606 Massey Dr/Infinity',
      streetAddress: '7606 Massey Dr',
      city: '44224',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1869',
      actualCompletion: '',
      actualStart: '',
      created: '44225.3722222222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '628',
      lotNumber: '58',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '12529 Whiskey River Rd/Infinity',
      streetAddress: '12529 Whiskey River Rd',
      city: '44223',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2526',
      actualCompletion: '',
      actualStart: '',
      created: '44225.3381944444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '364',
      garageSf: '1318',
      lotNumber: '15',
      parcelNumber: '126150615',
      permit: '',
      subdivisionAndPhase: 'Burns Estates Ph.2',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3730 Curtis Dr/Infinity',
      streetAddress: '3730 Curtis Dr',
      city: '44222',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44225.33125',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '721',
      lotNumber: '1',
      parcelNumber: '118981130000001',
      permit: '',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3711 Lakelse Ln/Pro Made',
      streetAddress: '3711 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44225.2840277778',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '47',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1586 3BSI8',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3811 Lakelse Ln/Pro Made',
      streetAddress: '3811 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44225.2722222222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '42',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1586 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7607 Coldwater Dr/Pro Made',
      streetAddress: '7607 Coldwater Dr',
      city: '44225',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44225.2666666667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '41',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1586 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7722 Coldwater Dr/Pro Made',
      streetAddress: '7722 Coldwater Dr',
      city: '44225',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44225.2604166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '20',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1586 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'No',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7714 Coldwater Dr/Pro Made',
      streetAddress: '7714 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '2349',
      actualCompletion: '',
      actualStart: '',
      created: '44223.2930555556',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '751',
      lotNumber: '18',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '2349 3BST8',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7715 Coldwater Dr/Pro Made',
      streetAddress: '7715 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44222.7513888889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '214',
      garageSf: '516',
      lotNumber: '36',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1586 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3608 Lakelse Ln/Pro Made',
      streetAddress: '3608 Lakelse Ln',
      city: '44224',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1598',
      actualCompletion: '',
      actualStart: '',
      created: '44222.7291666667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '143',
      garageSf: '742',
      lotNumber: '5',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1598 3BST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7612 Coldwater Dr/Pro Made',
      streetAddress: '7612 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1990',
      actualCompletion: '',
      actualStart: '',
      created: '44222.7145833333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '236',
      garageSf: '667',
      lotNumber: '14',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1990 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '765 Summit St/Infinity Lux',
      streetAddress: '765 Summit St',
      city: '44224',
      projectManager: 'Ruslan Gorbatyuk',
      scheduleStatus: 'Online',
      totalSqft: '3813',
      actualCompletion: '',
      actualStart: '',
      created: '44222.6840277778',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '1103',
      garageSf: '1047',
      lotNumber: '9',
      parcelNumber: '',
      permit: '44237',
      subdivisionAndPhase: 'Westcliffe Ph.XVI',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3605 Lakelse Ln/Pro Made',
      streetAddress: '3605 Lakelse Ln',
      city: '44225',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44222.6604166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '116',
      garageSf: '717',
      lotNumber: '52',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2BST9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7806 Waxwing Dr/Pro Made',
      streetAddress: '7806 Waxwing Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.6222222222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '116',
      garageSf: '481',
      lotNumber: '24',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2BST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7809 Coldwater Dr/Pro Made',
      streetAddress: '7809 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '',
      created: '44222.6138888889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '500',
      lotNumber: '31',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7711 Coldwater Dr/Pro Made',
      streetAddress: '7711 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44222.6006944444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '37',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44232',
      modelNumber: '1586 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7718 Coldwater Dr/Pro Made',
      streetAddress: '7718 Coldwater Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.5923611111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '468',
      lotNumber: '19',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 2AST8',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7805 Coldwater Dr/Pro Made',
      streetAddress: '7805 Coldwater Dr',
      city: '44223',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1507',
      actualCompletion: '',
      actualStart: '',
      created: '44222.5479166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '288',
      garageSf: '437',
      lotNumber: '32',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1507 2AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7807 Waxwing Dr/Pro Made',
      streetAddress: '7807 Waxwing Dr',
      city: '44223',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1507',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4805555556',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '288',
      garageSf: '630',
      lotNumber: '30',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44253',
      subdivisionAndPhase: 'Riverhawk Point II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1507 3BST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7611 Cassiar Dr/Pro Made',
      streetAddress: '7611 Cassiar Dr',
      city: '44223',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4777777778',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '468',
      lotNumber: '13',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1403 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7901 Waxwing Dr/Promade',
      streetAddress: '7901 Waxwing Dr',
      city: '44224',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4604166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '116',
      garageSf: '657',
      lotNumber: '28',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44253',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7719 Coldwater Dr/Pro Made',
      streetAddress: '7719 Coldwater Dr',
      city: '44223',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4555555556',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '657',
      lotNumber: '35',
      parcelNumber: '117511199 Parcel Parent',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 3BST9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3719 Lakelse Ln/Pro Made',
      streetAddress: '3719 Lakelse Ln',
      city: '44223',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1766',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4451388889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '262',
      garageSf: '635',
      lotNumber: '45',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1766 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3703 Lakelse Ln/Pro Made',
      streetAddress: '3703 Lakelse Ln',
      city: '44223',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1641',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4326388889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '166',
      garageSf: '625',
      lotNumber: '49',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1641 3BST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3505 Lakelse Ln/Promade',
      streetAddress: '3505 Lakelse Ln',
      city: '44222',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1766',
      actualCompletion: '',
      actualStart: '',
      created: '44222.4006944444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '262',
      garageSf: '695',
      lotNumber: '55',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1766 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'Yes',
      orderMaterial: 'No',
      orderOsb: 'Yes',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3715 Lakelse Ln/Pro Made',
      streetAddress: '3715 Lakelse Ln',
      city: '44222',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1507',
      actualCompletion: '',
      actualStart: '',
      created: '44222.3958333333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '288',
      garageSf: '633',
      lotNumber: '46',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1507 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7727 Coldwater Dr/Pro Made',
      streetAddress: '7727 Coldwater Dr',
      city: '44222',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '',
      created: '44222.3861111111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '33',
      parcelNumber: '117511199 parent parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1586 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '615 Athens Dr/Infinity',
      streetAddress: '615 Athens Dr',
      city: '44222',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1869',
      actualCompletion: '',
      actualStart: '44225',
      created: '44222.3770833333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44225',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '659',
      lotNumber: '23',
      parcelNumber: '101972030000025',
      permit: '44249',
      subdivisionAndPhase: 'Belmont Heights Ph.7',
      utilitiesPaid: '',
      utilitiesSent: '44232',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3803 Lakelse Ln/Pro Made',
      streetAddress: '3803 Lakelse Ln',
      city: '44222',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '2122',
      actualCompletion: '',
      actualStart: '',
      created: '44222.3694444444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '152',
      garageSf: '657',
      lotNumber: '44',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '2122 3ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7811 Waxwing Dr/Pro Made',
      streetAddress: '7811 Waxwing Dr',
      city: '44222',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '',
      created: '44222.325',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '657',
      lotNumber: '29',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '1403 3BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7810 Waxwing Dr/Promade',
      streetAddress: '7810 Waxwing Dr',
      city: '44217',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '44223',
      created: '44221.7784722222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44223',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '481',
      lotNumber: '25',
      parcelNumber: '117511199',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II PH.3',
      utilitiesPaid: '',
      utilitiesSent: '44232',
      modelNumber: '1403 2BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3620 Lakelse Ln/Pro made',
      streetAddress: '3620 Lakelse Ln',
      city: '44217',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1598',
      actualCompletion: '',
      actualStart: '44222',
      created: '44221.7701388889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44222',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '143',
      garageSf: '742',
      lotNumber: '8',
      parcelNumber: '117511199',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '',
      utilitiesSent: '44232',
      modelNumber: '1598 3AST9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7723 Coldwater Dr/Pro Made',
      streetAddress: '7723 Coldwater Dr',
      city: '44217',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '44222',
      created: '44221.7472222222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44222',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '214',
      garageSf: '516',
      lotNumber: '34',
      parcelNumber: '11751199',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.2',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '1586 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3547 Curtis Dr/Pro Made',
      streetAddress: '3547 Curtis Dr',
      city: '44217',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2349',
      actualCompletion: '',
      actualStart: '44218',
      created: '44221.7298611111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44218',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '691',
      lotNumber: 'Lot 15',
      parcelNumber: '118981130000015',
      permit: '',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '',
      utilitiesSent: '44232',
      modelNumber: '2349 3ASI9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7710 Coldwater Dr/ProMade',
      streetAddress: '7710 Coldwater Dr',
      city: '44216',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1598',
      actualCompletion: '',
      actualStart: '44218',
      created: '44217.4215277778',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44218',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '143',
      garageSf: '750',
      lotNumber: '17',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk pointe II Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1598 3AST9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7707 Coldwater Dr/ Pro Made',
      streetAddress: '7707 Coldwater Dr',
      city: '44215',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '1641',
      actualCompletion: '',
      actualStart: '44218',
      created: '44215.7458333333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44218',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '166',
      garageSf: '625',
      lotNumber: '38',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1641 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '635 Athens Dr/Infinity',
      streetAddress: '635 Athens Dr',
      city: '44215',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1986',
      actualCompletion: '',
      actualStart: '44215',
      created: '44215.7368055556',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44215',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '298',
      garageSf: '1,421',
      lotNumber: '22',
      parcelNumber: '101972050001000',
      permit: '44224',
      subdivisionAndPhase: 'Belmont Heights Ph. 7',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3613 Lakelse Ln/Pro Made',
      streetAddress: '3613 Lakelse Ln',
      city: '44214',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '44211',
      created: '44215.7270833333',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44211',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '50',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44232',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1586 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3609 Lakelse Ln/Promade',
      streetAddress: '3609 Lakelse Lane',
      city: '44211',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '44215',
      created: '44214.5534722222',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44215',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '116',
      garageSf: '468',
      lotNumber: 'Lot 51',
      parcelNumber: '117511199',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe ll Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1403 2BST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3601 Lakelse Ln/Pro Made',
      streetAddress: '3601 Lakelse Lane',
      city: '44211',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1507',
      actualCompletion: '',
      actualStart: '44211',
      created: '44214.5277777778',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44211',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '288',
      garageSf: '437',
      lotNumber: 'Lot 53',
      parcelNumber: '117511199',
      permit: '44252',
      subdivisionAndPhase: 'Riverhawk Pointe ll Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1507 2BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3509 Lakelse Lane/Pro Made',
      streetAddress: '3509 Lakelse Ln',
      city: '44214',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '44214',
      created: '44214.4798611111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44214',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '20',
      garageSf: '510',
      lotNumber: 'lot 54',
      parcelNumber: '117511199 Parent Parcel',
      permit: '44252',
      subdivisionAndPhase: 'Riverhawk Pointe ll Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1403 2BSI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '3807 Lakelse Ln/Pro Made',
      streetAddress: '3807 Lakelse Ln',
      city: '44214',
      projectManager: 'Francisco De-Leon',
      scheduleStatus: 'Online',
      totalSqft: '1586',
      actualCompletion: '',
      actualStart: '44214',
      created: '44214.4694444444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44214',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '182',
      garageSf: '637',
      lotNumber: '43',
      parcelNumber: '117511199 Parentt Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44217',
      modelNumber: '1586 3AST8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7167 Corsica St/Pro Made',
      streetAddress: '7167 Corsica St',
      city: '44209',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1641',
      actualCompletion: '',
      actualStart: '44213',
      created: '44209.4548611111',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44211',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '166',
      garageSf: '625',
      lotNumber: '8',
      parcelNumber: '101972040001000 Pearent Parcel',
      permit: '44223',
      subdivisionAndPhase: 'Belmont Heights Ph.6',
      utilitiesPaid: '',
      utilitiesSent: '44210',
      modelNumber: '1641 3ASI9',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '12530 Hunter/Infinity',
      streetAddress: '12530 Hunter Road',
      city: '44208',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2448',
      actualCompletion: '',
      actualStart: '44208',
      created: '44208.6576388889',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44208',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '396',
      garageSf: '818',
      lotNumber: '14',
      parcelNumber: '126150614',
      permit: '44252',
      subdivisionAndPhase: 'Burns Estates Ph.2 Lot 14',
      utilitiesPaid: '',
      utilitiesSent: '44236',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '7802 Waxwing Dr/Pro Made',
      streetAddress: '7802 Waxwing Dr',
      city: '44208',
      projectManager: 'Vlad Drigus',
      scheduleStatus: 'Online',
      totalSqft: '2046',
      actualCompletion: '',
      actualStart: '44209',
      created: '44208.6027777778',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44209',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '213',
      garageSf: '446',
      lotNumber: '23',
      parcelNumber: '117511199 Parent Parcel',
      permit: '',
      subdivisionAndPhase: 'Riverhawk Pointe II Ph.3',
      utilitiesPaid: '44228',
      utilitiesSent: '44210',
      modelNumber: '2046 2ASI8',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '803 Thebes St/Infinity',
      streetAddress: '803 Thebes Street',
      city: '44203',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2229',
      actualCompletion: '',
      actualStart: '44208',
      created: '44203.6604166667',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44208',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '239',
      garageSf: '667',
      lotNumber: 'Lot 3',
      parcelNumber: '101972040001000 Parent Parcel',
      permit: '44222',
      subdivisionAndPhase: 'Belmont Heights PH. 6',
      utilitiesPaid: '',
      utilitiesSent: '44210',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'Yes',
      orderLumber: 'Yes',
      orderMaterial: 'No',
      orderOsb: 'Yes',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'Yes'
    },
    {
      jobColor: '',
      jobName: '809 Thebes St/Pro Made',
      streetAddress: '809 Thebes St',
      city: '44203',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1990',
      actualCompletion: '',
      actualStart: '44207',
      created: '44203.6027777778',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44207',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '238',
      garageSf: '667',
      lotNumber: '4',
      parcelNumber: '1019720400100 Parent Parcel',
      permit: '44222',
      subdivisionAndPhase: 'Belmont Heights Ph.6',
      utilitiesPaid: '',
      utilitiesSent: '44210',
      modelNumber: '1990 3BST8',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '755 Thebes St/Infinity',
      streetAddress: '755 Thebes St',
      city: '44202',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2045',
      actualCompletion: '',
      actualStart: '44196',
      created: '44202.6208333333',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44196',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '229',
      garageSf: '710',
      lotNumber: '1',
      parcelNumber: '101972040001000 (Parent Parcel)',
      permit: '44209',
      subdivisionAndPhase: 'Belmont Heights PH.6',
      utilitiesPaid: '',
      utilitiesSent: '44204',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '777 Thebes St/Pro Made',
      streetAddress: '777 Thebes St',
      city: '44202',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1872',
      actualCompletion: '',
      actualStart: '44194',
      created: '44202.6055555556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44194',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '228',
      garageSf: '632',
      lotNumber: '2',
      parcelNumber: '101972040001000',
      permit: '44209',
      subdivisionAndPhase: 'Belmont Heights PH.6',
      utilitiesPaid: '44208',
      utilitiesSent: '44202',
      modelNumber: '1872 3BST9',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '*1507 2A',
      streetAddress: '',
      city: '',
      projectManager: '',
      scheduleStatus: 'Offline',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '44197',
      created: '44200.5868055556',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '44197',
      company: '',
      listingAgent: '',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: '',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '*1403 2A',
      streetAddress: '',
      city: '',
      projectManager: '',
      scheduleStatus: 'Online',
      totalSqft: '1403',
      actualCompletion: '',
      actualStart: '44197',
      created: '44196.3840277778',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '44197',
      company: '',
      listingAgent: '',
      coveredAreaSf: '',
      garageSf: '',
      lotNumber: '',
      parcelNumber: '',
      permit: '',
      subdivisionAndPhase: '',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3522 Curtis Dr/Infinity',
      streetAddress: '3522 Curtis Dr',
      city: '44194',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2229',
      actualCompletion: '',
      actualStart: '44194',
      created: '44194.6423611111',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44194',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '239',
      garageSf: '667',
      lotNumber: '13',
      parcelNumber: '118981130000013',
      permit: '44210',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '',
      utilitiesSent: '44195',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3610 Curtis Dr/Pro Made',
      streetAddress: '3610 Curtis Dr',
      city: '44194',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1872',
      actualCompletion: '',
      actualStart: '44193',
      created: '44194.6125',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44193',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '228',
      garageSf: '633',
      lotNumber: '6',
      parcelNumber: '118981130000006',
      permit: '44207',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '44208',
      utilitiesSent: '44195',
      modelNumber: '1872 3BSI9',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3636 Curtis Dr/Pro Made',
      streetAddress: '3636 Curtis Dr',
      city: '44188',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1766',
      actualCompletion: '',
      actualStart: '44189',
      created: '44188.5430555556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44189',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '262',
      garageSf: '635',
      lotNumber: '5',
      parcelNumber: '118981130000005',
      permit: '44195',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '44208',
      utilitiesSent: '',
      modelNumber: '1766 3BSI9',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3601 Curtis Dr/Infinity',
      streetAddress: '3601 Curtis Dr',
      city: '44188',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2460',
      actualCompletion: '',
      actualStart: '44190',
      created: '44188.2826388889',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44190',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '354',
      garageSf: '785',
      lotNumber: '18',
      parcelNumber: '118981130000018',
      permit: '44195',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '',
      utilitiesSent: '44193',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3529 Curtis Dr/Infinity',
      streetAddress: '3529 Curtis Dr',
      city: '44188',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2001',
      actualCompletion: '',
      actualStart: '44189',
      created: '44187.2756944444',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '44189',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '276',
      garageSf: '667',
      lotNumber: '14',
      parcelNumber: '118981130000014',
      permit: '44195',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '44208',
      utilitiesSent: '44193',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3625 Curtis Dr/Infinity',
      streetAddress: '3625 Curtis Dr',
      city: '44186',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2108',
      actualCompletion: '',
      actualStart: '44189',
      created: '44186.7298611111',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44189',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '683',
      lotNumber: '19',
      parcelNumber: '118981130000019',
      permit: '44195',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '44208',
      utilitiesSent: '44193',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7063 Corsica St/Infinity',
      streetAddress: '7063 Corsica St',
      city: '44186',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2108',
      actualCompletion: '',
      actualStart: '44188',
      created: '44183.54375',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44188',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '683',
      lotNumber: '13',
      parcelNumber: '101972050001000 (Parent Parcel)',
      permit: '44194',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44188',
      utilitiesSent: '44186',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7081 Corsica St/Pro Made',
      streetAddress: '7081 Corsica St',
      city: '44183',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1990',
      actualCompletion: '',
      actualStart: '44187',
      created: '44183.5375',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44187',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '238',
      garageSf: '667',
      lotNumber: '14',
      parcelNumber: '101972050001000 (Parent Parcel)',
      permit: '44208',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44188',
      utilitiesSent: '44186',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12528 Whiskey River Rd/Infinity',
      streetAddress: '12528 Whiskey River Rd',
      city: '44187',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2460',
      actualCompletion: '',
      actualStart: '',
      created: '44181.3229166667',
      status: 'OPEN',
      jobType: 'Presale',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '350',
      garageSf: '1586',
      lotNumber: '24',
      parcelNumber: '126150624',
      permit: '44229',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '44193',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7041 Corsica St/Infinity',
      streetAddress: '7041 Corsica St',
      city: '44181',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2229',
      actualCompletion: '',
      actualStart: '44187',
      created: '44180.3868055556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44187',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '239',
      garageSf: '667',
      lotNumber: '12',
      parcelNumber: '118981130000012',
      permit: '44219',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44183',
      utilitiesSent: '44181',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '3538 Curtis Dr/Pro Made',
      streetAddress: '3538 Curtis Dr',
      city: '44181',
      projectManager: 'Ruslan Gorbatyuk\nJesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1990',
      actualCompletion: '',
      actualStart: '44186',
      created: '44180.3395833333',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44186',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '236',
      garageSf: '667',
      lotNumber: '11',
      parcelNumber: '118981130000011',
      permit: '44194',
      subdivisionAndPhase: 'Sagewood Estates',
      utilitiesPaid: '44183',
      utilitiesSent: '44181',
      modelNumber: '1990 3BSI9',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7029 Corsica St/Pro Made',
      streetAddress: '7029 Corsica St',
      city: '44181',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '2349',
      actualCompletion: '',
      actualStart: '44183',
      created: '44179.7243055556',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44183',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '691',
      lotNumber: '11',
      parcelNumber: '101972050001000',
      permit: '44188',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44183',
      utilitiesSent: '44181',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12401 Whiskey River Rd/Infinity',
      streetAddress: '12401 Whiskey River Rd',
      city: '',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Offline',
      totalSqft: '2229',
      actualCompletion: '',
      actualStart: '',
      created: '44176.56875',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '239',
      garageSf: '667',
      lotNumber: '19',
      parcelNumber: '126150619',
      permit: '',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '',
      modelNumber: '',
      ccRs: 'Yes',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'No',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12402 Hunter Rd/Infinity',
      streetAddress: '12402 Hunter Rd',
      city: '44187',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2460',
      actualCompletion: '',
      actualStart: '',
      created: '44176.5652777778',
      status: 'OPEN',
      jobType: '',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '324',
      garageSf: '811',
      lotNumber: '10',
      parcelNumber: '126150610',
      permit: '44229',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '44193',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12413 Whiskey River Rd/Infinity',
      streetAddress: '12413 Whiskey River Rd',
      city: '44183',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2448',
      actualCompletion: '',
      actualStart: '',
      created: '44176.5583333333',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '396',
      garageSf: '818',
      lotNumber: '18',
      parcelNumber: '126150618',
      permit: '44229',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '44186',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12503 Whiskey River Rd/Infinity',
      streetAddress: '12503 Whiskey River Rd',
      city: '44183',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2428',
      actualCompletion: '',
      actualStart: '',
      created: '44176.5520833333',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '207',
      garageSf: '658',
      lotNumber: '17',
      parcelNumber: '126150617',
      permit: '44229',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '44186',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '7005 Corsica St/Infinity',
      streetAddress: '7005 Corsica St',
      city: '44174',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1801',
      actualCompletion: '',
      actualStart: '44182',
      created: '44173.4715277778',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44182',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '258',
      garageSf: '845',
      lotNumber: '10',
      parcelNumber: '10197205000100 Parent Parcel',
      permit: '44183',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44183',
      utilitiesSent: '44175',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '707 Athens Dr/Pro Made',
      streetAddress: '707 Athens Dr',
      city: '44174',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1766',
      actualCompletion: '',
      actualStart: '44181',
      created: '44173.4381944444',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44181',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '262',
      garageSf: '635',
      lotNumber: '20',
      parcelNumber: '101972050001000 Parent Parcel',
      permit: '44183',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44183',
      utilitiesSent: '44175',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '12412 Whiskey River Rd/Infinity',
      streetAddress: '12412 Whiskey River Rd',
      city: '44183',
      projectManager: 'Christian Anguiano',
      scheduleStatus: 'Online',
      totalSqft: '2272',
      actualCompletion: '',
      actualStart: '44193',
      created: '44172.3916666667',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44193',
      company: 'Infinity',
      listingAgent: 'Jane',
      coveredAreaSf: '248',
      garageSf: '1,786',
      lotNumber: '21',
      parcelNumber: '126150621',
      permit: '44229',
      subdivisionAndPhase: 'Burns Estates PH.2',
      utilitiesPaid: '',
      utilitiesSent: '44186',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'Yes',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '726 Athens Dr/Infinity',
      streetAddress: '726 Athens Dr',
      city: '44169',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '1986',
      actualCompletion: '',
      actualStart: '44180',
      created: '44169.4201388889',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44180',
      company: 'Infinity',
      listingAgent: 'Amy',
      coveredAreaSf: '298',
      garageSf: '1421',
      lotNumber: '8',
      parcelNumber: '101972050001000 Parent Parcel',
      permit: '44180',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44173',
      utilitiesSent: '44172',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    },
    {
      jobColor: '',
      jobName: '804 Athens Dr/Pro Made',
      streetAddress: '804 Athens Dr',
      city: '44169',
      projectManager: 'Jesse Martinez',
      scheduleStatus: 'Online',
      totalSqft: '',
      actualCompletion: '',
      actualStart: '44179',
      created: '44169.4138888889',
      status: 'OPEN',
      jobType: 'Spec',
      projCompletion: '',
      projStart: '44179',
      company: 'Promade',
      listingAgent: 'Amy',
      coveredAreaSf: '169',
      garageSf: '669',
      lotNumber: '9',
      parcelNumber: '101972050001000 Parent Parcel',
      permit: '44180',
      subdivisionAndPhase: 'Belmont Heights PH.7',
      utilitiesPaid: '44173',
      utilitiesSent: '44172',
      modelNumber: '',
      ccRs: 'No',
      floorJoists: 'No',
      orderLumber: 'No',
      orderMaterial: 'No',
      orderOsb: 'No',
      planReview: 'No',
      selections: 'Yes',
      trusses: 'No'
    }
  ]

export default homes;